export interface SeedCategory {
  name: string;
  slug: string;
  description: string;
  image: string;
  icon: string;
  featured: boolean;
  itemCount: number;
}

export interface SeedProduct {
  name: string;
  slug: string;
  description: string;
  price: string;
  compareAtPrice?: string;
  costPrice: string;
  stock: number;
  categorySlug: string;
  categoryName: string;
  brand: string;
  rating: string;
  reviewCount: number;
  images: string[];
  tags: string[];
  specs: Record<string, string>;
  colors: string[];
  sizes: string[];
  sku: string;
  isFeatured: boolean;
  isTrending: boolean;
  isNewArrival: boolean;
  status: string;
}

export const INITIAL_CATEGORIES: SeedCategory[] = [
  {
    name: "Audio & Acoustics",
    slug: "audio",
    description: "Studio-grade wireless headphones, noise-canceling earbuds, and audiophile sound systems.",
    image: "https://images.pexels.com/photos/577768/pexels-photo-577768.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    icon: "Headphones",
    featured: true,
    itemCount: 4,
  },
  {
    name: "Wearables & Tech",
    slug: "wearables",
    description: "Next-gen smartwatches, fitness trackers, and biometric wellness monitors.",
    image: "https://images.pexels.com/photos/9528216/pexels-photo-9528216.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    icon: "Watch",
    featured: true,
    itemCount: 4,
  },
  {
    name: "Fashion & Lifestyle",
    slug: "fashion",
    description: "Premium leather goods, designer sneakers, minimalist travel packs, and everyday essentials.",
    image: "https://images.pexels.com/photos/7821329/pexels-photo-7821329.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    icon: "ShoppingBag",
    featured: true,
    itemCount: 4,
  },
  {
    name: "Workspace & Desk",
    slug: "workspace",
    description: "Ergonomic accessories, mechanical keyboards, minimal desk pads, and productivity tools.",
    image: "https://images.pexels.com/photos/246340/pexels-photo-246340.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    icon: "Laptop",
    featured: true,
    itemCount: 4,
  },
  {
    name: "Home & Coffee",
    slug: "home-living",
    description: "Artisanal ceramic mugs, pour-over coffee gear, and sleek modern decor.",
    image: "https://images.pexels.com/photos/7622818/pexels-photo-7622818.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    icon: "Coffee",
    featured: true,
    itemCount: 4,
  },
  {
    name: "Self-Care & Wellness",
    slug: "wellness",
    description: "Organic skincare essentials, botanical serums, and restorative daily rituals.",
    image: "https://images.pexels.com/photos/4202321/pexels-photo-4202321.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    icon: "Sparkles",
    featured: true,
    itemCount: 4,
  },
];

export const INITIAL_PRODUCTS: SeedProduct[] = [
  {
    name: "Apex ANC Pro Wireless Studio Headphones",
    slug: "apex-anc-pro-headphones",
    description: "Engineered for pure audiophile precision. Features active hybrid noise cancellation (up to -42dB), custom 40mm beryllium drivers, 45-hour battery life, and plush memory foam earcups with aerospace aluminum accents.",
    price: "299.99",
    compareAtPrice: "379.99",
    costPrice: "140.00",
    stock: 24,
    categorySlug: "audio",
    categoryName: "Audio & Acoustics",
    brand: "ApexAudio",
    rating: "4.9",
    reviewCount: 128,
    images: [
      "https://images.pexels.com/photos/577768/pexels-photo-577768.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      "https://images.pexels.com/photos/32583519/pexels-photo-32583519.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      "https://images.pexels.com/photos/10703306/pexels-photo-10703306.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    ],
    tags: ["Headphones", "Wireless", "ANC", "Audiophile", "Bluetooth 5.3"],
    specs: {
      "Battery Life": "45 Hours (ANC On)",
      "Driver Type": "40mm Beryllium Diaphragm",
      "Connectivity": "Bluetooth 5.3 + 3.5mm Hi-Res Audio",
      "Weight": "260g",
      "Charging": "USB-C Quick Charge (10 min = 5 hrs)",
    },
    colors: ["Space Gray", "Matte Black", "Silver Frost"],
    sizes: ["Universal"],
    sku: "APX-HD-001",
    isFeatured: true,
    isTrending: true,
    isNewArrival: false,
    status: "active",
  },
  {
    name: "Aura Pods True Wireless Earbuds",
    slug: "aura-pods-wireless-earbuds",
    description: "Compact wireless earbuds with spatial audio tracking, crystal-clear 6-mic beamforming calls, and IPX7 sweat/water resistance. Includes wireless charging case with magnetic snap.",
    price: "149.00",
    compareAtPrice: "189.00",
    costPrice: "65.00",
    stock: 50,
    categorySlug: "audio",
    categoryName: "Audio & Acoustics",
    brand: "ApexAudio",
    rating: "4.8",
    reviewCount: 94,
    images: [
      "https://images.pexels.com/photos/10703306/pexels-photo-10703306.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      "https://images.pexels.com/photos/9528216/pexels-photo-9528216.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    ],
    tags: ["Earbuds", "Wireless", "Waterproof", "Spatial Audio"],
    specs: {
      "Playtime": "8 Hours (32 Hours with Case)",
      "Water Resistance": "IPX7 Certified",
      "Microphones": "6-mic ENC Array",
      "Charging": "Qi Wireless & USB-C",
    },
    colors: ["Obsidian Black", "Pearl White", "Sage Green"],
    sizes: ["S", "M", "L (Tips Included)"],
    sku: "APX-EP-002",
    isFeatured: true,
    isTrending: false,
    isNewArrival: true,
    status: "active",
  },
  {
    name: "Chronos Ultra Titanium Smartwatch",
    slug: "chronos-ultra-smartwatch",
    description: "Grade 5 Titanium bezel with 1.43-inch sapphire crystal AMOLED display. Continuous SpO2, ECG monitoring, GPS route tracking, and 14-day battery life. Built for extreme conditions and executive style.",
    price: "349.00",
    compareAtPrice: "420.00",
    costPrice: "180.00",
    stock: 18,
    categorySlug: "wearables",
    categoryName: "Wearables & Tech",
    brand: "ChronosTech",
    rating: "4.9",
    reviewCount: 76,
    images: [
      "https://images.pexels.com/photos/9528216/pexels-photo-9528216.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      "https://images.pexels.com/photos/32583519/pexels-photo-32583519.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    ],
    tags: ["Smartwatch", "Titanium", "Heart Rate", "GPS", "Water Resistant"],
    specs: {
      "Display": "1.43\" AMOLED 466x466 (Sapphire)",
      "Battery Life": "Up to 14 Days",
      "Sensors": "ECG, SpO2, Optical PPG, Barometer, Multi-Band GPS",
      "Water Resistance": "10 ATM (100m)",
    },
    colors: ["Titanium Gray", "Midnight Black", "Desert Sand"],
    sizes: ["46mm", "42mm"],
    sku: "CHR-SW-001",
    isFeatured: true,
    isTrending: true,
    isNewArrival: false,
    status: "active",
  },
  {
    name: "NovaPulse Biometric Smart Ring",
    slug: "novapulse-smart-ring",
    description: "Featherlight titanium smart ring measuring sleep staging, recovery scores, heart rate variability (HRV), and body temperature trends without the distraction of screens.",
    price: "249.00",
    compareAtPrice: "299.00",
    costPrice: "110.00",
    stock: 35,
    categorySlug: "wearables",
    categoryName: "Wearables & Tech",
    brand: "ChronosTech",
    rating: "4.7",
    reviewCount: 48,
    images: [
      "https://images.pexels.com/photos/3184451/pexels-photo-3184451.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      "https://images.pexels.com/photos/9528216/pexels-photo-9528216.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    ],
    tags: ["Smart Ring", "Sleep Tracker", "Recovery", "Titanium"],
    specs: {
      "Material": "Grade 5 Titanium with PVD Coating",
      "Battery": "7 Days Continuous",
      "Weight": "4 grams",
      "App Support": "iOS & Android (No Monthly Subscription)",
    },
    colors: ["Stealth Matte Black", "Brushed Silver", "Rose Gold"],
    sizes: ["US 7", "US 8", "US 9", "US 10", "US 11", "US 12"],
    sku: "NOV-RG-003",
    isFeatured: false,
    isTrending: true,
    isNewArrival: true,
    status: "active",
  },
  {
    name: "Artisan Full-Grain Leather Weekender Duffle",
    slug: "artisan-leather-weekender-bag",
    description: "Handcrafted from vegetable-tanned Italian calfskin with solid brass hardware, YKK Excella zippers, water-resistant twill lining, and a dedicated padded 16\" laptop compartment.",
    price: "280.00",
    compareAtPrice: "350.00",
    costPrice: "120.00",
    stock: 12,
    categorySlug: "fashion",
    categoryName: "Fashion & Lifestyle",
    brand: "LuxeCraft",
    rating: "4.9",
    reviewCount: 88,
    images: [
      "https://images.pexels.com/photos/7821329/pexels-photo-7821329.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      "https://images.pexels.com/photos/4168430/pexels-photo-4168430.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      "https://images.pexels.com/photos/1204464/pexels-photo-1204464.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    ],
    tags: ["Leather", "Travel", "Bag", "Handcrafted", "Luxury"],
    specs: {
      "Material": "Full-Grain Italian Calfskin Leather",
      "Dimensions": "20.5\" x 11.5\" x 10\"",
      "Capacity": "40 Liters",
      "Laptop Sleeve": "Fits up to 16\" MacBook Pro",
    },
    colors: ["Cognac Brown", "Espresso Dark Brown", "Onyx Black"],
    sizes: ["One Size (40L)"],
    sku: "LX-BAG-001",
    isFeatured: true,
    isTrending: true,
    isNewArrival: false,
    status: "active",
  },
  {
    name: "Stride Velocity Pro Urban Sneakers",
    slug: "stride-velocity-urban-sneakers",
    description: "Engineered knit upper with responsive nitrogen-infused foam midsole for all-day cloud-like cushioning. Minimalist silhouette perfect for city commuting and gym sessions.",
    price: "135.00",
    compareAtPrice: "165.00",
    costPrice: "55.00",
    stock: 45,
    categorySlug: "fashion",
    categoryName: "Fashion & Lifestyle",
    brand: "StrideLab",
    rating: "4.8",
    reviewCount: 112,
    images: [
      "https://images.pexels.com/photos/11324524/pexels-photo-11324524.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      "https://images.pexels.com/photos/9287167/pexels-photo-9287167.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    ],
    tags: ["Sneakers", "Footwear", "Athletic", "Breathable"],
    specs: {
      "Midsole": "Supercritical Nitrogen Foam",
      "Upper": "100% Recycled Engineered Knit",
      "Outsole": "High-Traction Vibram Rubber",
      "Weight": "245g (Size 9)",
    },
    colors: ["Chalk White", "Triple Black", "Crimson Pulse"],
    sizes: ["US 8", "US 9", "US 10", "US 11", "US 12"],
    sku: "STR-SNK-002",
    isFeatured: true,
    isTrending: false,
    isNewArrival: true,
    status: "active",
  },
  {
    name: "Aerolight Canvas & Leather Everyday Tote",
    slug: "aerolight-canvas-leather-tote",
    description: "Heavyweight 18oz water-repellent organic cotton canvas paired with bridle leather straps. Features magnetic closure, interior zip pocket, and key leash.",
    price: "95.00",
    compareAtPrice: "120.00",
    costPrice: "38.00",
    stock: 30,
    categorySlug: "fashion",
    categoryName: "Fashion & Lifestyle",
    brand: "LuxeCraft",
    rating: "4.7",
    reviewCount: 39,
    images: [
      "https://images.pexels.com/photos/17334077/pexels-photo-17334077.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      "https://images.pexels.com/photos/1204464/pexels-photo-1204464.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    ],
    tags: ["Tote", "Canvas", "Eco-Friendly", "Bag"],
    specs: {
      "Material": "18oz Organic Duck Canvas + Full Grain Trim",
      "Dimensions": "16\" x 14\" x 5\"",
      "Pockets": "3 interior, 1 zippered security pocket",
    },
    colors: ["Natural Ecru", "Olive Green", "Charcoal Gray"],
    sizes: ["Standard (18L)"],
    sku: "LX-TOT-003",
    isFeatured: false,
    isTrending: false,
    isNewArrival: true,
    status: "active",
  },
  {
    name: "ErgoFlow Precision Mechanical Keyboard",
    slug: "ergoflow-mechanical-keyboard",
    description: "75% custom layout wireless mechanical keyboard with CNC aluminum case, gasket mount dampening, factory-lubed linear switches, and per-key RGB backlighting. Bluetooth 5.2 and 2.4GHz dongle included.",
    price: "189.00",
    compareAtPrice: "229.00",
    costPrice: "85.00",
    stock: 22,
    categorySlug: "workspace",
    categoryName: "Workspace & Desk",
    brand: "NovaDesk",
    rating: "4.9",
    reviewCount: 65,
    images: [
      "https://images.pexels.com/photos/246340/pexels-photo-246340.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      "https://images.pexels.com/photos/4087178/pexels-photo-4087178.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    ],
    tags: ["Keyboard", "Mechanical", "Wireless", "Workspace", "Hot-Swappable"],
    specs: {
      "Switch Type": "Gateron Oil King (Linear, Lubed)",
      "Keycaps": "Double-Shot PBT Cherry Profile",
      "Battery": "4000mAh (Up to 200 hours without backlight)",
      "Case": "6063 Anodized CNC Aluminum",
    },
    colors: ["Space Navy", "Moonlight White", "Industrial Slate"],
    sizes: ["75% Layout"],
    sku: "NVD-KB-001",
    isFeatured: true,
    isTrending: true,
    isNewArrival: false,
    status: "active",
  },
  {
    name: "Minimalist Leather Desk Pad & Cable Rail",
    slug: "minimalist-leather-desk-pad",
    description: "Dual-sided premium vegan leather desk blotter with magnetic cable organizing rail. Protects desk surface while creating a polished, distraction-free work environment.",
    price: "48.00",
    compareAtPrice: "65.00",
    costPrice: "18.00",
    stock: 60,
    categorySlug: "workspace",
    categoryName: "Workspace & Desk",
    brand: "NovaDesk",
    rating: "4.8",
    reviewCount: 42,
    images: [
      "https://images.pexels.com/photos/4087178/pexels-photo-4087178.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      "https://images.pexels.com/photos/6633803/pexels-photo-6633803.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    ],
    tags: ["Desk Pad", "Organizer", "Leather", "Workspace"],
    specs: {
      "Dimensions": "35.4\" x 16.5\" (Large)",
      "Material": "Waterproof PU Leather + Non-slip felt base",
      "Includes": "2 Magnetic Cable Clips",
    },
    colors: ["Caramel Tan", "Midnight Black", "Forest Green"],
    sizes: ["Medium (31x12)", "Large (35x16)", "Extra Large (47x20)"],
    sku: "NVD-PAD-002",
    isFeatured: false,
    isTrending: true,
    isNewArrival: false,
    status: "active",
  },
  {
    name: "Artisan Pour-Over Goose Neck Barista Kettle",
    slug: "artisan-barista-gooseneck-kettle",
    description: "Precision temperature control kettle (104°F - 212°F) with counterbalanced walnut wood handle, LCD real-time thermometer, and 60-minute temperature hold mode for the ultimate cup of coffee.",
    price: "165.00",
    compareAtPrice: "199.00",
    costPrice: "72.00",
    stock: 20,
    categorySlug: "home-living",
    categoryName: "Home & Coffee",
    brand: "BaristaCraft",
    rating: "4.9",
    reviewCount: 95,
    images: [
      "https://images.pexels.com/photos/7622818/pexels-photo-7622818.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      "https://images.pexels.com/photos/6754875/pexels-photo-6754875.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    ],
    tags: ["Coffee", "Kettle", "Kitchen", "Smart Home", "Stainless Steel"],
    specs: {
      "Capacity": "0.9 Liters (30 oz)",
      "Power": "1200W Rapid Boil System",
      "Material": "304 Food-Grade Stainless Steel + Solid Walnut",
      "Features": "Built-in Brew Stopwatch, PID Temp Controller",
    },
    colors: ["Matte Black with Walnut", "Brushed Steel with Oak", "Warm Sand"],
    sizes: ["0.9L Standard"],
    sku: "BC-KTL-001",
    isFeatured: true,
    isTrending: false,
    isNewArrival: true,
    status: "active",
  },
  {
    name: "Handcrafted Terracotta & Ceramic Mug Set",
    slug: "handcrafted-ceramic-mug-set",
    description: "Set of 2 artisan-thrown ceramic mugs with textured speckled glaze and ergonomic thumb rest. Microwave and dishwasher safe, crafted by independent ceramic artisans.",
    price: "42.00",
    compareAtPrice: "55.00",
    costPrice: "16.00",
    stock: 40,
    categorySlug: "home-living",
    categoryName: "Home & Coffee",
    brand: "BaristaCraft",
    rating: "4.8",
    reviewCount: 52,
    images: [
      "https://images.pexels.com/photos/4466240/pexels-photo-4466240.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      "https://images.pexels.com/photos/6754875/pexels-photo-6754875.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      "https://images.pexels.com/photos/3493049/pexels-photo-3493049.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    ],
    tags: ["Ceramics", "Mug", "Handmade", "Kitchen", "Coffee"],
    specs: {
      "Capacity": "14 oz (410 ml)",
      "Material": "Stoneware Clay & Mineral Glaze",
      "Care": "Dishwasher & Microwave Safe",
      "Set Size": "2 Mugs Included",
    },
    colors: ["Speckled Sand", "Midnight Slate", "Terracotta Blush"],
    sizes: ["14 oz (Set of 2)"],
    sku: "BC-MUG-002",
    isFeatured: false,
    isTrending: true,
    isNewArrival: false,
    status: "active",
  },
  {
    name: "Lumière Botanical Restorative Serum & Facial Oil",
    slug: "lumiere-botanical-restorative-serum",
    description: "Formulated with cold-pressed squalane, niacinamide, marula oil, and blue tansy extract. Deeply hydrates, balances skin microbiome, and imparts an ethereal glow without pore clogging.",
    price: "68.00",
    compareAtPrice: "85.00",
    costPrice: "24.00",
    stock: 55,
    categorySlug: "wellness",
    categoryName: "Self-Care & Wellness",
    brand: "Lumière Botanicals",
    rating: "4.9",
    reviewCount: 140,
    images: [
      "https://images.pexels.com/photos/4202321/pexels-photo-4202321.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      "https://images.pexels.com/photos/26605943/pexels-photo-26605943.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    ],
    tags: ["Skincare", "Organic", "Hydration", "Serum", "Cruelty-Free"],
    specs: {
      "Volume": "50ml / 1.7 fl oz",
      "Skin Type": "All Skin Types (Sensitive Safe)",
      "Key Ingredients": "Niacinamide 5%, Plant Squalane, Blue Tansy, Hyaluronic Acid",
      "Certification": "100% Vegan & Leaping Bunny Certified",
    },
    colors: ["Amber Glass Bottle"],
    sizes: ["50ml (Standard)", "100ml (Value Size)"],
    sku: "LUM-SRM-001",
    isFeatured: true,
    isTrending: true,
    isNewArrival: false,
    status: "active",
  },
];

export const INITIAL_COUPONS = [
  {
    code: "SAVE15",
    description: "15% off your entire order",
    discountType: "percent",
    discountValue: "15.00",
    minSpend: "50.00",
    maxDiscount: "100.00",
    isActive: true,
  },
  {
    code: "APEX20",
    description: "20% VIP Storewide Discount",
    discountType: "percent",
    discountValue: "20.00",
    minSpend: "100.00",
    maxDiscount: "200.00",
    isActive: true,
  },
  {
    code: "SUMMER50",
    description: "$50 off high-ticket orders over $250",
    discountType: "fixed",
    discountValue: "50.00",
    minSpend: "250.00",
    isActive: true,
  },
  {
    code: "FREESHIP",
    description: "Free Priority Shipping on any order",
    discountType: "fixed",
    discountValue: "15.00",
    minSpend: "30.00",
    isActive: true,
  },
];

export const INITIAL_REVIEWS = [
  {
    productSlug: "apex-anc-pro-headphones",
    userName: "Alexander Wright",
    rating: 5,
    title: "Best ANC headphones I have ever used!",
    comment: "The build quality feels like a $600 pair of studio monitors. The beryllium drivers deliver deep, tight bass and sparkling highs without fatigue. Battery lasted me through an entire week of flights and daily coding sessions.",
    verifiedPurchase: true,
    helpfulCount: 42,
  },
  {
    productSlug: "apex-anc-pro-headphones",
    userName: "Elena Rostova",
    rating: 5,
    title: "Incredible comfort and acoustic isolation",
    comment: "Memory foam ear cushions are ultra-soft even with glasses. Noise cancellation wipes out city traffic and loud office chatter completely.",
    verifiedPurchase: true,
    helpfulCount: 19,
  },
  {
    productSlug: "chronos-ultra-smartwatch",
    userName: "Marcus Chen",
    rating: 5,
    title: "Titanium craftsmanship is outstanding",
    comment: "The sapphire glass has zero scratches after weeks of trail running. Battery lasts an honest 12-14 days on a single charge. The health metrics are surprisingly accurate compared to medical devices.",
    verifiedPurchase: true,
    helpfulCount: 28,
  },
  {
    productSlug: "artisan-leather-weekender-bag",
    userName: "Sophia Lorenzi",
    rating: 5,
    title: "Stunning leather aroma and craftsmanship",
    comment: "Real full-grain leather that has already begun to develop a gorgeous patina. Fits my 16 inch MacBook Pro, 3 outfits, shoes, and toiletries effortlessly.",
    verifiedPurchase: true,
    helpfulCount: 35,
  },
  {
    productSlug: "ergoflow-mechanical-keyboard",
    userName: "David K.",
    rating: 5,
    title: "Thocky, smooth, and breathtaking typing experience",
    comment: "The pre-lubed Gateron Oil Kings sound like gentle raindrops. Gasket mount flex is sublime. Seamless transition between Mac and Windows.",
    verifiedPurchase: true,
    helpfulCount: 21,
  },
  {
    productSlug: "lumiere-botanical-restorative-serum",
    userName: "Chloe Bennett",
    rating: 5,
    title: "Holy grail skincare discovery",
    comment: "My redness vanished after 4 days. It absorbs immediately leaving a velvety dewy finish without any oily residue. Will be repurchasing repeatedly!",
    verifiedPurchase: true,
    helpfulCount: 57,
  },
];
